# Generated by Django 5.2.7 on 2026-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_folder_deleted_at_alter_folder_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
