# Generated by Django 5.2.7 on 2026-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_folder_deleted_at_alter_folder_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
