# Generated by Django 5.2.7 on 2026-09-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_folder_is_deleted_userfile_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTransactionHistory',
        ),
    ]
