# Generated by Django 5.2.7 on 2026-09-13 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_usertransactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='plan_validity',
            field=models.PositiveIntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.package'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateField()),
                ('active_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('Expired', 'Expired'), ('ON_QUEUE', 'On Queue')], default='ACTIVE', max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subscription'),
        ),
    ]
